#! /usr/bin/perl

use strict;
use Mail::Postfixadmin;
use Getopt::Std;

my %opt;
getopts("h", \%opt);
if($opt{'h'}){
	print usage();
	exit;
}


my $pfa = Mail::Postfixadmin->new();

my @domains = $pfa->getDomains;

print join("\n", @domains);
print "\n";

sub usage{
return <<EOF;

pfa_listdomains

   lists domains configured on the system

Usage: 

  pfa_listdomains

EOF
}

=pod

=head1 NAME

pfa_listdomains - list domains configured on the system

=head1 DESCRIPTION

This is part of Avi's collection of scripts to emulate vpopmail's scripts 
on a Postfix/MySQL system; postfixadmin-tools

=head1 SYNOPSIS

pfa-listdomains

Options:
  none

=head1 EXAMPLES

list domains:
 pfa-listdomains

=head1 EXIT STATUS

0: success or nothing to do
2: tried to proceed, failed somewhere

=head1 BUGS

Should be reported on GitHub:
    https://github.com/BigRedS/postfixadmin-tools/issues

=head1 AUTHOR

Avi wrote this.

http://avi.co

http://github.com/BigRedS/postfixadmin-tools

