#! /usr/bin/perl

use strict;
use Mail::Postfixadmin;

my $pfa = Mail::Postfixadmin->new();
my $user = $ARGV[0];
if ( $user eq '' ){
	print "Error: I need a user\n";
	exit 1;
}

unless( $pfa->userExists($user) ){
	print STDERR "$user doesn't exist\n";
	exit 1;
}

my ($local,$domain) = split(/@/, $user);
if($pfa->domainIsAlias($domain)){
	$domain = $pfa->getAliasDomainTarget($domain);
}

# Handle aliases gracefully:
my $olduser;
if( $pfa->userIsAlias($user) ){
	my $target = join("\n\t", $pfa->getAliasUserTargets($user));
	if ($target =~ /\n/){
		print "$user is an alias for:\n\t$target\n";
		exit 1;
	}else{
		print "$user is an alias for $target\n";
		$olduser = $user;
		$user = $target;
	}
	if ($pfa->userExists($user)){
		print "\n";
	}else{
		print " which is not configured on this system\n";
	}
}

# To avoid confusion post the alias dealings, we'll reset our idea
# of the user
$user =~ /@(.+)$/;
my $domain = $1;
if ( $pfa->domainIsAlias($domain) ){
	my $targetDomain = $pfa->getAliasDomainTarget($domain);
	$user =~ s/$domain/$targetDomain/;
}
my $info = $pfa->getUserInfo($user);
foreach( sort(keys(%$info)) ){
	unless($_ =~ /^mailboxes$/){
		printf('%-14s%s', $_, $info->{$_});
		print "\n";
	}
}


=pod

=head1 NAME

vuserinfo - get information about a user

=head1 DESCRIPTION

This is part of Avi's collection of scripts to emulate vpopmail's 
scripts on a Postfix/MySQL system. 

Any feature-parity is purely coincidental.

=head1 SYNOPSIS

vuserinfo user@domain.com

=head1 OPTIONS

No.

=head1 EXAMPLES

View the details of user@example.net:
  vuserinfo example.net

=head1 EXIT STATUS

Exits 0 on success, non-zero on failure. Useful error messages are used 
as a poor substitute for sensible exit statuses.

=head1 AUTHOR

Avi wrote this.

http://avi.co

http://github.com/BigRedS/vpostmail

