#! /usr/bin/perl

use Mail::Postfixadmin;
use Getopt::Std;

use strict;

my %opt;
getopts('vf', \%opt);
if($opt{'h'}){
	print usage();
	exit;
}

my $domain = shift;

if($domain =~ /^$/){
	print STDERR "No domain passed\n\n";
	print STDERR usage();
	exit 1;
}

if($domain =~ /@/){
	print STDERR "That looks like an email address, not a domain; aborting\n";;
	exit 1;
}

my $pfa = Mail::Postfixadmin->new();

if( $pfa->domainExists( $domain )){
	print STDERR "Domain $domain already configured; aborting\n";
	exit 0;
}

if($pfa->createDomain( domain => $domain)){
	print $domain if exists($opt{v});
}else{
	print "Unknown Error creating domain $domain: $@";
	exit 2;
}

exit 0;

sub usage{
	my $message = shift;
	my $return;
	if($message){
		$return.="\n\nERROR: $message";
	}

return <<EOF;
$return

Adds a domain to the mail system. 

Usage:

  vadddomain <domain>

Exit values:
 0: success or nothing to do
 1: bad arguments
 2: error

EOF
}

=pod

=head1 NAME

pfa_adddomain - add a domain to the system

=head1 DESCRIPTION

This is part of Avi's collection of scripts to emulate vpopmail's scripts 
on a Postfix/MySQL system; postfixadmin-tools

=head1 SYNOPSIS

pfa-adddomain [options] domain name

Options:
   -v    be verbose; print the name of the domain name when it's created.

=head1 EXAMPLES

add example.net:
 pfa-adddomain example.net

=head1 EXIT STATUS

0: success or nothing to do (domain exists)
1: bad arguments
2: tried to proceed, failed somewhere

=head1 BUGS

Should be reported on GitHub:
    https://github.com/BigRedS/postfixadmin-tools/issues

=head1 AUTHOR

Avi wrote this.

http://avi.co

http://github.com/BigRedS/postfixadmin-tools

